### ISSUE TITLE
modify the file header part of aggsig code

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/rust-secp256k1-zkp#34]
Corresponding to https://github.com/mimblewimble/secp256k1-zkp/issues/29

There're also 2 files in this repo:
- aggsig.rs
- pedersen.rs

I guess there's no any upstream for these 2 source files. Could you please confirm this?  @yeastplume 

I also suggest to change the header part, currently it's:
```
// Bitcoin secp256k1 bindings
// Written in 2014 by
//   Dawid Ciężarkiewicz
//   Andrew Poelstra
//
```

And one more suggestion:  Could we do rustfmt on these 2 files?  since there's no upstream for these 2 files and no need to worry merging.

**Comment by yeastplume** [comment]
okay, done
