### ISSUE TITLE
Test pedersen::tests::test_bullet_proof_multisig fails

### ISSUE THREAD

**Issue by jaspervdm** [mimblewimble/rust-secp256k1-zkp#40]
Just did a `cargo test`, the `pedersen::tests::test_bullet_proof_multisig` fails

**Comment by garyyu** [comment]
I run a test to loop 10,000 times for `test_bullet_proof_multisig`, with the current version (SHA1 ID: 304ef7264a0dd9ef4efaaa0e28480cb030c18265), no any failure.

perhaps already fixed by some commits, so let's close this one :-)
