### ISSUE TITLE
Bump version and upload to crates.io

### ISSUE THREAD

**Issue by bddap** [mimblewimble/rust-secp256k1-zkp#45]
Recent changes, namely deriving `Serialize` and `Deserialize` for `Error` are not yet published to crates.io. It would be great if they were.

**Comment by bddap** [comment]
This needs to be done by one of the crate owners: @ignopeverell or @yeastplume.

<img width="371" alt="screen shot 2019-02-25 at 1 48 47 pm" src="https://user-images.githubusercontent.com/2702854/53371145-55952180-3904-11e9-840c-ab50058e6b53.png">

**Comment by ignopeverell** [comment]
Looking at a couple PRs on https://github.com/mimblewimble/secp256k1-zkp, once they're done I think we can do a new release.

**Comment by bddap** [comment]
Any news on this? This is--in a roundabout way--blocking grin apiv2 development.

**Comment by ignopeverell** [comment]
Released 0.7.5: https://crates.io/crates/grin_secp256k1zkp
