### ISSUE TITLE
whereis secp256k1_bulletproof_rangeproof_prove defined?

### ISSUE THREAD

**Issue by jackzhp** [mimblewimble/rust-secp256k1-zkp#61]
I just can not find where the function secp256k1_bulletproof_rangeproof_prove is defined.
anyone can help me?

I assume it goes with this project:

https://github.com/ElementsProject/secp256k1-zkp/tree/secp256k1-zkp/src

thanks.

**Comment by jaspervdm** [comment]
Grin uses a fork of that repository. You can find the definition of that function [here](https://github.com/mimblewimble/secp256k1-zkp/blob/master/src/modules/bulletproofs/main_impl.h#L184)

**Comment by jackzhp** [comment]
really appreciated. thanks.
