### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by jackzhp** [mimblewimble/rust-secp256k1-zkp#77]
I am new to rust.

after I got the repository, I run

cargo build

then I got 

error: no such file or directory: 'depend/secp256k1-zkp/contrib/lax_der_parsing.c'

what should I do? Can someone please help.

**Comment by quentinlesceller** [comment]
`git submodule update` ?

**Comment by ndcroos** [comment]
I tried also to build this, and I executed `git submodule update`.
Maybe instructions can be added to the README.md on how to build this project.
